-- Code generated by modelgen; DO NOT EDIT.
CREATE TABLE IF NOT EXISTS menus (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    path TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
