package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
)

type column struct {
	Name       string
	Type       string
	NotNull    bool
	PrimaryKey bool
	Unique     bool
	Default    string
}

func main() {
	inputPath := flag.String("input", "", "path to the Go source file that contains the model")
	typeName := flag.String("type", "", "name of the struct type to convert")
	outPath := flag.String("out", "", "output SQL migration file")
	flag.Parse()

	if *inputPath == "" || *typeName == "" || *outPath == "" {
		log.Fatal("ต้องระบุ -input, -type และ -out")
	}

	columns, tableName, err := loadColumns(*inputPath, *typeName)
	if err != nil {
		log.Fatal(err)
	}

	if tableName == "" {
		tableName = snakeCase(*typeName) + "s"
	}

	output := renderMigration(tableName, columns)
	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		log.Fatalf("ไม่สามารถสร้างโฟลเดอร์ปลายทางได้: %v", err)
	}

	if err := os.WriteFile(*outPath, []byte(output), 0o644); err != nil {
		log.Fatalf("ไม่สามารถเขียน migration ได้: %v", err)
	}

	log.Printf("✅ generated %s", *outPath)
}

func loadColumns(inputPath, typeName string) ([]column, string, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, inputPath, nil, parser.ParseComments)
	if err != nil {
		return nil, "", fmt.Errorf("ไม่สามารถ parse model file ได้: %v", err)
	}

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok || typeSpec.Name.Name != typeName {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				return nil, "", fmt.Errorf("%s ไม่ใช่ struct", typeName)
			}

			columns := make([]column, 0, len(structType.Fields.List))
			for _, field := range structType.Fields.List {
				if len(field.Names) == 0 {
					continue
				}

				fieldName := field.Names[0].Name
				col := column{Name: snakeCase(fieldName)}
				col.Type, col.NotNull, col.PrimaryKey, col.Unique, col.Default = inferColumn(fieldName, field.Type, field.Tag)
				columns = append(columns, col)
			}

			return columns, snakeCase(typeName) + "s", nil
		}
	}

	return nil, "", fmt.Errorf("ไม่พบ type %s ในไฟล์ %s", typeName, inputPath)
}

func inferColumn(fieldName string, expr ast.Expr, tag *ast.BasicLit) (string, bool, bool, bool, string) {
	columnType := "TEXT"
	notNull := false
	primaryKey := false
	unique := false
	defaultValue := ""

	if fieldName == "ID" {
		columnType = "UUID"
		primaryKey = true
		notNull = true
	}

	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			columnType = "TEXT"
		case "bool":
			columnType = "BOOLEAN"
		}
	case *ast.SelectorExpr:
		if pkg, ok := t.X.(*ast.Ident); ok && pkg.Name == "time" && t.Sel.Name == "Time" {
			columnType = "TIMESTAMPTZ"
		}
	}

	if tag != nil {
		tagValue, err := strconv.Unquote(tag.Value)
		if err == nil {
			dbTag := reflect.StructTag(tagValue).Get("db")
			parts := strings.Split(dbTag, ",")
			for _, part := range parts {
				part = strings.TrimSpace(part)
				if part == "" {
					continue
				}

				switch {
				case part == "primarykey":
					primaryKey = true
					notNull = true
				case part == "notnull":
					notNull = true
				case part == "nullable":
					notNull = false
				case part == "unique":
					unique = true
				case strings.HasPrefix(part, "default:"):
					defaultValue = strings.TrimPrefix(part, "default:")
				case part == "uuid" || part == "text" || part == "boolean" || part == "timestamptz":
					columnType = strings.ToUpper(part)
				}
			}
		}
	}

	return columnType, notNull, primaryKey, unique, defaultValue
}

func renderMigration(tableName string, columns []column) string {
	var buf bytes.Buffer
	buf.WriteString("-- Code generated by modelgen; DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n", tableName))

	parts := make([]string, 0, len(columns))
	for _, col := range columns {
		line := fmt.Sprintf("    %s %s", col.Name, col.Type)
		if col.PrimaryKey {
			line += " PRIMARY KEY"
		}
		if col.NotNull && !col.PrimaryKey {
			line += " NOT NULL"
		}
		if col.Unique {
			line += " UNIQUE"
		}
		if col.Default != "" {
			line += " DEFAULT " + col.Default
		}
		parts = append(parts, line)
	}

	buf.WriteString(strings.Join(parts, ",\n"))
	buf.WriteString("\n);\n")
	return buf.String()
}

func snakeCase(value string) string {
	if strings.ToUpper(value) == value {
		return strings.ToLower(value)
	}

	var out []rune
	for i, r := range value {
		if i > 0 && r >= 'A' && r <= 'Z' {
			out = append(out, '_')
		}
		out = append(out, r)
	}
	return strings.ToLower(string(out))
}
