const SESSION_TIMEOUT_HOURS = Number(import.meta.env.VITE_SESSION_TIMEOUT_HOURS ?? '6')
export const SESSION_TIMEOUT_MS =
  Number.isFinite(SESSION_TIMEOUT_HOURS) && SESSION_TIMEOUT_HOURS > 0
    ? SESSION_TIMEOUT_HOURS * 60 * 60 * 1000
    : 6 * 60 * 60 * 1000

const IDLE_TIMEOUT_HOURS = Number(import.meta.env.VITE_IDLE_TIMEOUT_HOURS ?? '1')
export const IDLE_TIMEOUT_MS =
  Number.isFinite(IDLE_TIMEOUT_HOURS) && IDLE_TIMEOUT_HOURS > 0
    ? IDLE_TIMEOUT_HOURS * 60 * 60 * 1000
    : 60 * 60 * 1000
